### ISSUE TITLE
UpdateSceneAsync() serializes Id wrong

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#103]
`HueResults x = await Client.UpdateSceneAsync(SelectedScene.Id, SelectedScene);`

results in:

`{"**Id**":"GQiJIITMPFDgx66","name":"TesterScene","lights":["1","4","6"]}`

Response: 
`[{"error":{"type":6,"address":"/scenes/GQiJIITMPFDgx66/Id","description":"parameter, Id, not available"}}]`

**Comment by michielpost** [comment]
Fixed in version 3.3.1
