### ISSUE TITLE
.Net standard library version?

### ISSUE THREAD

**Issue by wind-rider** [Q42/Q42.HueApi#107]
Do you have plans to support a .net core / .net standard library version?

**Comment by michielpost** [comment]
I already did some work on that a year ago, it's on this branch:
https://github.com/Q42/Q42.HueApi/tree/feature/netstandard

But there was so much unclear at that time, I'm going to delete that branch and start over.

My plan was to start as soon as someone needed it. I'll start working on it this week.

**Comment by michielpost** [comment]
The netstandard version of Q42.HueApi and Q42.HueApi.ColorConverters is now on NuGet (version 3.4.0)
Let me know if you find any problems.

**Comment by wind-rider** [comment]
Great, I'll try it! Thank you!

**Comment by wind-rider** [comment]
First impressions are good
