### ISSUE TITLE
Error converting value "Entertainment" to type 'Q42.HueApi.Models.Groups.GroupType'.

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#109]
I came across this error in my crash analytics. Looks like a user has some sort of group that has Entertainment as its type (no idea how...).

What would be the best solution for this? To default it to LightGroup in case a Type is unknown?

**Comment by michielpost** [comment]
Type can be null, I made a change to ignore unknown enum values
It's on NuGet in release 3.4.1
