### ISSUE TITLE
SSDPBridgeLocater removed?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#110]
Was the SSDPBridgeLocated removed from the main package for UWP? Installing the Q42.HueApi.WinRT solved the issue, just wanted to check!

**Comment by michielpost** [comment]
The main package used to include the WinRT package if your target was a Windows app. But with the new Visual Studio 2017 / netstandard setup this has changed. You now have to manually include the WinRT package.. So this is ok, but I'll update the docs / description.

**Comment by niels9001** [comment]
Clear, thanks!
