### ISSUE TITLE
Q42.HueApi.ColorConverters is removed in version 3.4.1

### ISSUE THREAD

**Issue by Rep-Hueman** [Q42/Q42.HueApi#111]
I get a Error on ColorConverters in version 3.4.X

Error	CS0234	The type or namespace name 'ColorConverters' does not exist in the namespace 'Q42.HueApi' (are you missing an assembly reference?)

![fout-q42](https://cloud.githubusercontent.com/assets/28707705/26059399/f207f242-3981-11e7-8b1c-9097abf34f51.jpg)

**Comment by niels9001** [comment]
Color converts are part of a separate NuGet package. Is this one added? (You basically need Q42.HueApi, and Q42.HueApi.ColorConverters)

**Comment by Rep-Hueman** [comment]
Yes thank you..
It is working now.
