### ISSUE TITLE
ZigBee channel cannot be updated?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#113]
Seems that the BridgeConfigUpdate does not allow to set the ZigBee channel although the official API documentation does describe the possibility to do this. E.g.
`      await Client.UpdateBridgeConfigAsync(new BridgeConfigUpdate() { ZigbeeChannel = 15 });`

**Comment by michielpost** [comment]
Can you point me to the documentation that says this can be updated?

Can't find it on https://www.developers.meethue.com/documentation/configuration-api#73_modify_configuration

**Comment by niels9001** [comment]
Ah, it's indeed not listed under Modify configuration.

Although, here it says:

> zigbeechannel	string	1.3	The current wireless frequency channel used by the bridge. **It can take values of 11, 15, 20,25 or 0 if undefined (factory new)**.



This code works:

PUT to api/username/config with:
`{
"zigbeechannel": 20
}`

`[
	{
		"success": {
			"/config/zigbeechannel": 20
		}
	}
]`

**Comment by niels9001** [comment]
I reached out to the Philips team, and they have added the Zigbeechannel description in the documentation: https://www.developers.meethue.com/documentation/configuration-api#73_modify_configuration

> zigbeechannel | string | The wireless frequency channel used by the bridge. It can take values of 11, 15, 20 or 25. | Optional

**Comment by michielpost** [comment]
Thanks for he update. I've added the ZigbeeChannel to the BridgeConfigUpdate model.

**Comment by niels9001** [comment]
Any idea when the NuGet package is coming with this fix included?

**Comment by michielpost** [comment]
It's on NuGet now, version 3.4.4
