### ISSUE TITLE
BridgeConfig (swupdate.devicetypes. (bridg and lights and sensors missing))

### ISSUE THREAD

**Issue by Rep-Hueman** [Q42/Q42.HueApi#115]
I can not use this value from the Brige

Config.SoftwareUpdate.devicetypes.bridg = ....
Config.SoftwareUpdate.devicetypes.lights = ....
Config.SoftwareUpdate.devicetypes.sensors = ....

**Comment by Rep-Hueman** [comment]
[incomming-json.txt](https://github.com/Q42/Q42.HueApi/files/1072074/incomming-json.txt)

**Comment by michielpost** [comment]
Fixed in commit: https://github.com/Q42/Q42.HueApi/commit/5d238fbe2375cf413eaba62cf54bca9a7697da0b
Available in version 3.4.3 now on NuGet
