### ISSUE TITLE
Swupdate2 - new way for software updating with API version 1.20

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#116]
Looks like there are quite some changes to do the configuration API: swupdate2 has been added.

https://developers.meethue.com/documentation/configuration-api

Changelog: https://www.developers.meethue.com/documentation/changelog

**Comment by niels9001** [comment]
Nice! What is the best practice - check if API version is 1.19 or lower and use the 'obsolete' way, else use the new attributes?

**Comment by michielpost** [comment]
Yes, normally I would remove the obsolte properties. But in this case they can be useful for old bridges to update to the latest version. I'll remove them at some point in the future.

**Comment by niels9001** [comment]
Just an update. I read on the Hue API forums that the Gen1 bridge will stay at API version 1.16. It might make sense to keep the older properties so we can still use older API calls for the first gen Bridge.

> Hi,

Thanks for the note and documentation is updated.  Gen1 remains at 1.16 due to its limited bridge resources and Gen2 will continue to receive latest updates. 


Hue Developer Support - Walter

**Comment by michielpost** [comment]
Version 3.5.0 with these changes is now on NuGet
