### ISSUE TITLE
Compatibility with TRÅDFRI

### ISSUE THREAD

**Issue by Bodmoor** [Q42/Q42.HueApi#122]
Hello,

I was curious to know if this library is compatible with the TRÅDFRI bridge 'out-of-the-box', or if any plans exist to add this compatibility.

Kind regards, Paul Segerink

**Comment by michielpost** [comment]
This library is for communicating with the Hue bridge, if your Tradfri lights are on the Hue bridge, it should work. There are currently no plans to make this library compatible with the Tradfri bridge.

I might make something for the Tradfri bridge in the future, but that'll be a new library seperate from this one.
