### ISSUE TITLE
Install in .net 4.6.2 project

### ISSUE THREAD

**Issue by tgiachi** [Q42/Q42.HueApi#123]
Why when i'm installing in .net 4.6.2. project, install everything of .net standard library?

**Comment by michielpost** [comment]
Yes, that's because Q42.HueApi targets .Net Standard. It's recommended to have a dependency on the NetStandard Metapackage.
Also see: https://stackoverflow.com/questions/43995354/reducing-dependencies-for-a-net-standard-class-library

**Comment by tgiachi** [comment]
Ok thanks, @michielpost ! Is possibile to generate nuget package target framework without .net standard framework dependency and leave only Json?

**Comment by michielpost** [comment]
No, I don't think so?

**Comment by tgiachi** [comment]
Ok, thank you anyway

**Comment by leo60228** [comment]
@michielpost This issue is somewhat old, but this appears to be possible. Simply change
```
    <TargetFramework>netstandard2.0</TargetFramework>
```
in each `.csproj` to:
```
    <TargetFrameworks>netstandard2.0;net45</TargetFramework>
```
This is documented at https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks. I'll submit a PR soon.

**Comment by leo60228** [comment]
#178
