### ISSUE TITLE
Philips introduces HueSDK

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#124]
Philips introduced the HueSDK with a Windows version as well (it is however a DLL wrapped around a JAR it seems), and only working on 86/64.. Looks pretty legacy to me.

Anything we could learn from it? (Like the multi-Bridge approach)?

https://github.com/PhilipsHue/HueSDK

https://developers.meethue.com/documentation/hue-sdk

**Comment by michielpost** [comment]
I had a quick look at it, but it looks like it's a Java SDK that also works with Java Desktop apps. It's not a .Net SDK.

I didn't see anything about the multi Bridge support, can you point a link to that?

**Comment by niels9001** [comment]
Ah, its listed in the Q&A that I forgot to post: https://developers.meethue.com/documentation/whyshows-whats-new-hue-sdk

> **New features in Hue SDK?**
Multi-bridge support with persistent simultaneous bridge connections
Fast connection mode
Persistent Bridge State in DB
Rule Builder – Simplifies rule creation
Rule Parser – Simplifies rule interpretation
Schedule Builder – Simplifies schedule creation
Color Space Conversion – CT<-> RGB RGB<->HSV
Heartbeat Manager – Polling period enforcement
Automatic re-connection to Hue bridges
Automatic start of authentication process when not authenticated
Complete Hue API support, including Hue Remote API with valid credentials
Continued future feature support as new features become available
