### ISSUE TITLE
Error converting value "readytoinstall" to type 'Q42.HueApi.SoftwareUpdateState'

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#125]
![image](https://user-images.githubusercontent.com/9866362/31460383-89eb626a-aec6-11e7-81dd-555312d1beae.png)

Seems that swupdate2 has some new state types.

https://developers.meethue.com/documentation/software-update

**Comment by michielpost** [comment]
The value `readytoinstall` is not documented anywhere?
The possible values of swupdate2.bridge.state are not documented at all. I've assumed they were the same as swupdate.state values.

https://developers.meethue.com/documentation/configuration-api#72_get_configuration

I can add the value readytoinstall for now.

**Comment by niels9001** [comment]
I think they are listed on a different page (for some reason...)

https://developers.meethue.com/documentation/software-update

SwUpdate2 states:

![image](https://user-images.githubusercontent.com/9866362/31485868-a3ce967e-af35-11e7-84dd-183bf1c753bc.png)


The deprecated (but still relevant for Bridge V1 users, they will not update to 1.19 or higher) SwUpdate1 states are still the same:

![image](https://user-images.githubusercontent.com/9866362/31485903-c95d4f2a-af35-11e7-9859-b065da6f75d8.png)

**Comment by niels9001** [comment]
Oh wait - you're right. 'readytoinstall' is not listed anywhere..

I'll check with the Hue team.

**Comment by niels9001** [comment]
@michielpost is the above fix also part of the latest NuGet package?

**Comment by niels9001** [comment]
https://developers.meethue.com/documentation/software-update

Developer documentation has been updated with the correct states.

**Comment by michielpost** [comment]
Thanks, added an additional value and updated the NuGet package to 3.5.1
