### ISSUE TITLE
API version 1.22 returns new light attributes

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#131]
Looks like 1.22 returns new attributes. Can't find anything on the documentation just yet, nor in the API changelog. I'll reach out to the Hue team to see when this will be added so it can be added to the Q42.HueApi as well!

> "1": {
> 		"state": {
> 			"on": true,
> 			"bri": 144,
> 			"hue": 13548,
> 			"sat": 200,
> 			"effect": "none",
> 			"xy": [
> 				0.5015,
> 				0.4153
> 			],
> 			"ct": 443,
> 			"alert": "none",
> 			"colormode": "xy",
> 			**"mode": "homeautomation",**
> 			"reachable": true
> 		},
> 		**"swupdate": {
> 			"state": "noupdates",
> 			"lastinstall": "2017-11-15T13:15:41"
> 		},**
> 		"type": "Extended color light",
> 		"name": "Floor",
> 		"modelid": "LCT001",
> 		"manufacturername": "Philips",
> 		**"capabilities": {
> 			"streaming": {
> 				"renderer": true,
> 				"proxy": false
> 			}
> 		},**
> 		"uniqueid": "00:17:88:01:00:e1:0a:68-0b",
> 		"swversion": "5.105.0.21169"
> 	}

**Comment by michielpost** [comment]
Added the new properties. Will be available in the next version.
