### ISSUE TITLE
new bulbmodels missing in colorconverter

### ISSUE THREAD

**Issue by vandenbrakel** [Q42/Q42.HueApi#132]
CIE1931Gamut.cs misses some new models resulting in wrong output:

Gamut A missing:     
"LLC014" /* Bloom, Aura (gen III) */

Gamut C missing:
 "LCT010" /* Hue A19 gen 3 */,
"LCT014" /* Hue A19 gen 3 */,
"LCT015" /* Hue A19 gen 3 */,
 "LCT016" /* Hue A19 gen 3 */

**Comment by michielpost** [comment]
Thanks, they have been added. Will be available in the next release.
