### ISSUE TITLE
Entertainment GroupType

### ISSUE THREAD

**Issue by vandenbrakel** [Q42/Q42.HueApi#134]
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/Models/Groups/Group.cs has
New "Entertainment" Group missing in GroupType;

Thanks.

/// <summary>
	/// Possible group types
	/// </summary>
	public enum GroupType
	{
		
		[EnumMember(Value = "LightGroup")]
		LightGroup,
		[EnumMember(Value = "Room")]
		Room,
		[EnumMember(Value = "Luminaire")]
		Luminaire,
		[EnumMember(Value = "LightSource")]
		LightSource
	}

**Comment by michielpost** [comment]
Hue Entertainment support is available in release 3.6.0
https://github.com/Q42/Q42.HueApi/releases/tag/3.6.0

Check out the new Q42.HueApi.Entertainment documentation https://github.com/Q42/Q42.HueApi/blob/master/EntertainmentApi.md
