### ISSUE TITLE
API 1.23 firmware

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#137]
Upcoming Hue bridge firmware release.
In the coming weeks, we will roll out a new Hue bridge firmware update (1.23). The update does not contain Hue API changes but does contain a number of internal changes. One such change is the new HTTP server component through which all commands are transferred. This new HTTP server is stricter in handling requests compared to the previous one, e.g. a HOST header field is required in all HTTP/1.1 request messages per RFC. This can impact your application due to non-functional behavioural changes or stricter handling of requests. We kindly would like to ask you to test this new release with your integration.

------------

Would this impact Q42.HueApi? If not, we can close this issue of course :)

**Comment by michielpost** [comment]
I expect the .Net HttpClient to do proper HTTP requests, so there should be no problem. I checked and the HOST header field is being included.

I'll close this issue. Let me know if there are any problems when the new firmware is released.

**Comment by nesherman** [comment]
Niels, is there a direct link to download Huetro outside of the Microsoft Store? I'm not sure where else to contact you. Thanks, and have a great day.
