### ISSUE TITLE
Change of room type not possible

### ISSUE THREAD

**Issue by darkprojekt** [Q42/Q42.HueApi#138]
Hi

I would like to change the room type in the UpdateGroupAsync methode. Did I miss something or is it currently not supported?

`UpdateGroupAsync(string id, IEnumerable<string> lights, string name = null)
`

The bridge API seems to allow the change of the room type:

2.4. Set group attributes
`class string 1..32 As of 1.11 : Category of the Room type. Default is "Other".` 
[https://www.developers.meethue.com/documentation/groups-api#24_set_group_attributes](https://www.developers.meethue.com/documentation/groups-api#24_set_group_attributes)

Could you have please a look if it would be possible to add?

Thanks & have a good day
Michael

**Comment by michielpost** [comment]
Thanks, fixed and now on NuGet Q42.HueApi.3.6.1
