### ISSUE TITLE
UpdateGroupAsync results in parameter, /groups/{id}/type, is not modifiable

### ISSUE THREAD

**Issue by darkprojekt** [Q42/Q42.HueApi#140]
Hi 

When calling UpdateGroupAsync to update a group (room), then I get along with success for lights, name and class the error "/groups/{id}/type, is not modifiable".

According to the signature of the method the type should not be changed and the [hue API is not supporting to change the type at all](https://www.developers.meethue.com/documentation/groups-api#24_set_group_attributes):

`await client.UpdateGroupAsync(id, lights, name, class);`

Could you have a look at this?
Thanks for your great work!

Michael

**Comment by michielpost** [comment]
Thanks, should be fixed in version 3.6.2, now on NuGet
