### ISSUE TITLE
parameter {1} is duplicated twice thereby ignoring the third parameter

### ISSUE THREAD

**Issue by Sleezly** [Q42/Q42.HueApi#141]
https://github.com/Q42/Q42.HueApi/blob/8ee5b33be17ffc0884042b24187c3050eff518af/src/Q42.HueApi/HueClient-Scenes.cs#L214

**Comment by Sleezly** [comment]
The 'lightstate' portion of the URI after the second {1} should also be changed to 'state'.  See 4.3 'Modify Scene' for details:
https://developers.meethue.com/documentation/scenes-api#43_modify_scene

Example URI:
{http://192.168.x.x/api/{user_key}/scenes/{scene_id}/lights/{light_id}/state}

**Comment by Sleezly** [comment]
Pull Request has been submitted:
URI fix for ModifySceneAsync #142

Thanks.

**Comment by michielpost** [comment]
Fixed with #PR142 and released on NuGet Q42.HueApi 3.6.3
