### ISSUE TITLE
DeleteScene() returns null

### ISSUE THREAD

**Issue by Deery5000** [Q42/Q42.HueApi#143]
Hi, 

Im trying to delete all scenes from the bridge however when i call client.DeleteScene(scene.Id) the HueResults returns null and the scene is not deleted.

Any ideas on this ?

**Comment by michielpost** [comment]
Are you using the correct scene ID?
I just tested this and it works fine.

You can run this test script:
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi.Tests/SceneTests.cs#L44-L64

DeleteScene indeed returns null, but that's not a problem, the scene is deleted.

**Comment by Deery5000** [comment]
Default scenes are deleted but not all of them, 4 remain
