### ISSUE TITLE
Polling Movement Sensor

### ISSUE THREAD

**Issue by jimmywyatt** [Q42/Q42.HueApi#148]
Hi, this isn't really an issue, but whats the best way to poll the movement sensor to find out if someone is there? check State.Presence every .5 seconds? is there a push event of any sort?

**Comment by michielpost** [comment]
The Philips Hue Bridge does not support push events through the public developer api. So polling is currently your best option.

**Comment by jimmywyatt** [comment]
Thanks, is that likely to drain the sensors battery or, i suppose you're only polling the hub which will only be updated when the sensor changes.
