### ISSUE TITLE
What is State.Brightness supposed to represent?

### ISSUE THREAD

**Issue by S0L4REDEV** [Q42/Q42.HueApi#149]
I realized that the brightness of my lamp when using the API was 159 when using the State.Brightness value. I was really confused what this meant and was hoping I could get an answer.

Thanks and sorry for the trouble.

**Comment by niels9001** [comment]
Brightness goes from 0 (very dimmed) up to 255 (very bright). Check the official Hue documentation here for more info: https://www.developers.meethue.com

 Hope this helps

**Comment by S0L4REDEV** [comment]
@niels9001 Thanks! I also bought your app! :)
