### ISSUE TITLE
HttpBridgeLocator URL Update

### ISSUE THREAD

**Issue by mgpreston** [Q42/Q42.HueApi#151]
Thanks for the great library!

According to https://www.developers.meethue.com, the URL of the HTTP bridge locator service has changed, and should now point to `https://discovery.meethue.com`:

> Bridge Discovery Endpoint Change
--
Effective July 1 (nupnp) bridge discovery is supported by a new endpoint, which is https://discovery.meethue.com. The old endpoint  www.meethue.com/api/nupnp   has been deprecated but remains available until further notice. We had  to change to the new endpoint such that we can guarantee a high  reliability with the increased amount of traffic we are getting. There  are no other differences besides the url. If you experience issues,  please let us know

As an aside, it seems [SSDPBridgeLocator](https://github.com/Q42/Q42.HueApi/blob/ac19f1fb5e59c9463a7105ff2478f03b1b9f4527/src/Q42.HueApi.NET/SSDPBridgeLocator.cs#L56) has a `Thread.Sleep` in the `LocateBridgesAsync` method, which would probably be better as `await Task.Delay`.

**Comment by michielpost** [comment]
Thanks. Updated and will be in the next release.
