### ISSUE TITLE
Adding a group of type LightGroup fails with "parameter, class, not available"

### ISSUE THREAD

**Issue by igor-grant** [Q42/Q42.HueApi#153]
First off, thank you for your hard work on this library.  It has saved me countless hours integrating with the Philips Hue API.

Whenever I call the Q42 CreateGroupAsync method with a GroupType of LightGroup and a RoomClass of null, the Hue API responds with "parameter, class, not available".  I replicated this with Fiddler directly to the Hue API and found that the it requires the entire RoomClass node to be missing from the JSON payload (null) if the GroupType is LightGroup.  It appears as though the Q42 method sets a default value for this property ("Other") regardless of the GroupType.  Could you please only include this property in the JSON if the GroupType is Room?

Thanks,
Grant

**Comment by michielpost** [comment]
Thanks! Bugfix for this is now available on NuGet version 3.7.1

**Comment by igor-grant** [comment]
Thanks!
