### ISSUE TITLE
No lights with Philips Hue Bridge v1.0

### ISSUE THREAD

**Issue by StefanRademakers** [Q42/Q42.HueApi#155]
From the latest release of Q42 VERSION 3.7.2 users are reporting an issue where they don't have any lights show up. These users all have the old v1.0 bridge. (Some with the latest firmware).

Is this a known issue or a conscious decision?

Thank for the info/ feedback.

Best Regards, Stefan

**Comment by michielpost** [comment]
I don't have an old v1.0 bridge, but the API should be the same on both bridges. 
`GetLightsAsync` works fine on my current bridge and there haven't been any big changes recently to GetLightsAsync as far as I know.

If you can post a JSON response from a v1.0 bridge I can check it out.

**Comment by StefanRademakers** [comment]
Hello Michiel,

Installed the v1 bridge and did a test (needed to borrow one ;)). 
It's seems to be an internal problem. We convert the Light object to a generic type in our app. 
And I presumed the ArcheType would always be present on the Config of the Light.

This fixed my issue:
if (light.Config!=null && light.Config.ArcheType!=null) {
    bulb.ArcheType = light.Config.ArcheType;
}

Thanks for the quick response and sorry for wasting some of your time.

Best Regards, Stefan

**Comment by michielpost** [comment]
Ok, no problem, I'm glad it's fixed.
