### ISSUE TITLE
System.Runtime couldn't load at Startup

### ISSUE THREAD

**Issue by MalauD** [Q42/Q42.HueApi#156]
Hello,
so in my project, i'm using a control dedicated for an hue interface and i have an issue with the dependency of Q42 when the control load. It exactly say: `System.IO.FileNotFoundException : 'Couldn't load the file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' one ofde it dependency.`

Note that i did the following things:
- Re-install Q42.HueApi with it dependencies
- Directly remove and add the reference to System.Runtime from facades of .NET

I hope i'm enough clear otherwise ask me for more details 😄 

By the way thanks for this amazing library 😉

**Comment by michielpost** [comment]
Can you create a small project which can reproduce this error, so I can have a look?
Is your app running on the .Net framework? Version 4.1? Or something else?

**Comment by michielpost** [comment]
Yes, please show me the project so I can reproduce it. Thanks.

**Comment by MalauD** [comment]
So the control library is here [https://github.com/MusicsOnlinePlayer/MusicsOnlinePlayer/tree/master/ControlLibrary/User%20Interface](url) and the control is called `HueControl.cs`

**Comment by michielpost** [comment]
I downloaded the project and I can run the ControlLibrary project. Select the HueControl and press connect. After that I receive some error about a config XML file. But that seems unrelated to the Hue library.

How can I reproduce this error?

**Comment by michielpost** [comment]
When I create the XML file, the control still loads correct. 
I can click the Connect button and I see a list of all my Hue lights.

**Comment by michielpost** [comment]
.Net Framework 4.7.1
Runtime v4.0.30319
Q42.HueApi Version 3.7.2.0

It's your repository without any modifications.
