### ISSUE TITLE
New light properties (startup mode)

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#158]
With the latest Hue app and light bulb firmware the startup mode can now be set.

According to the documentation (https://developers.meethue.com/develop/hue-api/supported-devices/#Supported-lights) the new modes are:

`
Startup object attributes
--
  | mode | enum | 1.26 | Mode of the startup behavior
  | safety | lights go back to Philips “bright light” safety setting (100% brightness @ 2700K)
  | powerfail | light keeps the setting when power failed. If light was off it stays off
  | lastonstate | light keeps the setting when power failed. If light was off it returns to the last on state
  | custom | custom settings defined in custom settings. Will be automatically set when providing “customsettings”.Not available for “On/Off Light”
  | unknown | custom setting is not supported
  | configured | bool | 1.28 | true if the startup settings are committed to the device, false if not.If this attribute is not present (<1.28) the bridge does not ensure the settings are committed
`

The app itself only allows setting the Safety and Powerfail mode.

**Comment by michielpost** [comment]
New NuGet packages are available (v3.8.1) with this functionality included.
