### ISSUE TITLE
Entertainment Api Light Bulb always turned off

### ISSUE THREAD

**Issue by KristinnVikarJ** [Q42/Q42.HueApi#164]
I'm Trying to implement the Entertainment API into my program but everytime It connects the bulb just turns off completely meaning I cannot interact with it, the code i use to connect is just a copy paste of the sample 'StreamingSetup.cs' and to change the light I copy pasted the code from 'HueStreaming.cs'

Do I need to configure something special or am I doing something wrong?

**Comment by michielpost** [comment]
The default state is off, so it probably means your connection to the bridge is ok.
After creating the connection, create an EffectLayer (baselayer) and apply some effects on that layer, like SetRandomColor or FlashQuick.
