### ISSUE TITLE
Q42.HueApi.Tests minor bug

### ISSUE THREAD

**Issue by kundelstein** [Q42/Q42.HueApi#168]
Hi. Since I just started playing with HueApi, I wrote down some things which IMHO need some love, one of them is this:

Test method in Q42.HueApi.Tests won't work as expected.

In the function 
`public async Task CheckConnectionWrongKeyTest()`
the result will be always false, regardless the key being right or wrong. The function `client.CheckConnection()` will return false unless client has been initialized/registered before, this is not happening in this test.

**Comment by michielpost** [comment]
The initialization is happening in the Initialize method which has the TestInitialize attribute.
This method calls the constructor of LocalHueClient with ip and key and then the client is initialized.

**Comment by kundelstein** [comment]
My bad, sorry - didn't notice that.
