### ISSUE TITLE
Errors when trying to use groupscenes

### ISSUE THREAD

**Issue by akutruff** [Q42/Q42.HueApi#171]
I tried using - https://github.com/Q42/Q42.HueApi/issues/161

There are semantic changes when attempting to use group scenes.  There was an enum verficiation bug due to the value being an integer, as well as errors when trying to manipulate the scene.  Hue didn't document groupscenes well, so expected behavior is challenging to discern.

I apologize for not having exacts as I forgot to file the bug when I was investigating.

**Comment by michielpost** [comment]
Can you be more specific? What are you trying to do?
Create a GroupScene using CreateGroupAsync?
What error did you receive?
