### ISSUE TITLE
System.Net.Sockets.SocketException at _hueStreamingClient.Close()

### ISSUE THREAD

**Issue by sasharp** [Q42/Q42.HueApi#172]
Hello,

I am using Streaming API on Xamarin.Forms and it works fine. But when I try to close a connection by `_hueStreamingClient.Close()` it gets **System.Net.Sockets.SocketException**. What is the right way to stop streaming?

**Comment by michielpost** [comment]
Thanks. Also noticed this but just used a try catched. It's not fixed by using a Shutdown and Close on the socket instead of a Disconnect(). New version is up on NuGet.
