### ISSUE TITLE
Alarm status is parsed wrong when updating alarm

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#175]
I'm getting an error when trying to set the IsEnabled status of a Schedule.

> {"name":"Name","description":"","command":{"address":"/api/ID/groups/8/action","method":"PUT","body":{"bri":255,"on":false}},"localtime":"W127/T15:30:00","status":1}

Response:

> [{"error":{"type":7,"address":"/schedules/3/status","description":"invalid value, 1}, for parameter, status"}}]

Seems that the status is set to 1 instead of 'disabled'.

**Comment by michielpost** [comment]
Thanks, fixed it in version 3.8.4, now on NuGet

**Comment by niels9001** [comment]
Cool, thanks!
