### ISSUE TITLE
StreamingHueClient does not implement IDisposable

### ISSUE THREAD

**Issue by AngusMcIntyre** [Q42/Q42.HueApi#183]
`StreamingHueClient` has a method named `Close` but does not implement `IDisposable`. This does not seem idiomatic.
Given that `Close` [appears to release unmanaged resources](https://github.com/Q42/Q42.HueApi/blob/7f0e719cbeb84f45e0969e6db210376eb8c47866/src/Q42.HueApi.Streaming/StreamingHueClient.cs#L47-L52) I feel that it is appropriate to implement `IDisposable`. 

Any objections?

**Comment by michielpost** [comment]
Yes, I think you're right.

**Comment by AngusMcIntyre** [comment]
PR submitted https://github.com/Q42/Q42.HueApi/pull/184
