### ISSUE TITLE
InnerException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by joao7yt** [Q42/Q42.HueApi#186]
Until yesterday it was working fine... Another thing I notice is that if I try to access https://discovery.meethue.com/ manually on the browser it warns me it's insecure...

![Untitled](https://user-images.githubusercontent.com/10665193/59512061-42479b00-8e8e-11e9-9b7b-2e9bd131d2bd.png)

**Comment by michielpost** [comment]
Looks like they just renewed the certificate.
It works fine on my machine. It says the certificate is valid from  7-6-2019 until 14-6-2021

**Comment by joao7yt** [comment]
Oh, and forgot to mention; I still can control the lights just fine through my phone and the Hue app... So I think it has something to do with the way you handle accessing the discovery

**Comment by joao7yt** [comment]
In this case, how can I help you figuring out why for me it’s not working?

**Comment by michielpost** [comment]
Can you try to access https://discovery.meethue.com/ in your browser from another computer? The site does not say it's insecure here. Maybe there is some proxy running like Fiddler that causes this.

**Comment by joao7yt** [comment]
I’m at work now, but will try in a few hours... the weird thing it that a few hours ago, when I was working in my app, it was working flawlessly. I don’t have such apps in my machine and didn’t install any yesterday...

I also tried to disconnect everything from power and turning it on again to see if it would renew connections and so on...

**Comment by joao7yt** [comment]
Just realized I can access discovery not only from the same network as the hub, I’m dumb sorry... It will output the same message as it was when I was home:
![A397E482-4C9F-45DD-95DE-682693CAEE78](https://user-images.githubusercontent.com/10665193/59514821-0f080a80-8e94-11e9-89fb-b9895ca19d04.png)

**Comment by joao7yt** [comment]
Seems like something to do with timezones... But anyway, as the Hue app is capable of working just fine, I don't see why you could not bypass this InnerException in some way... 

check it out: https://stackoverflow.com/questions/11222759/error-c-sharp-the-underlying-connection-was-closed-could-not-establish-trust-r

or this: https://social.msdn.microsoft.com/Forums/en-US/7e9e4582-8332-41b2-a33a-44f4417a3ad6/c-the-underlying-connection-was-closed-could-not-establish-trust-relationship-for-the-ssltls?forum=csharpgeneral

**Comment by michielpost** [comment]
Yes, but I'm not going to ignore this exception in the library. It's a valid exception that the SSL certificate can't be trusted so ignore the response from the server.

**Comment by joao7yt** [comment]
I think you could add a bool variable in LocateBridgesAsync like "bool ignoreSsl = false" or something, that if true would ignore the warning. This way we could then choose if we we want to bypass it or not.

Otherwise the api wouldn't be necessary at all as I would need to do it manually...
