### ISSUE TITLE
Remote Api don't works anymore

### ISSUE THREAD

**Issue by tgiachi** [Q42/Q42.HueApi#188]
In remote auth flow when i try to get Token, the result token is null

```csharp
var response = _remoteAuthentication.ProcessAuthorizeResponse(result.RequestUrl);
var token = await _remoteAuthentication.GetToken(response.Code);
```

where `response` is valid code response

Thanks!

**Comment by michielpost** [comment]
I'll have a look at this issue this week. Thanks.

**Comment by michielpost** [comment]
Can you test using the Q42.HueApi.RemoteApi.Sample in this repo?
Fill in your appId, clientid, clientSecret and callbackUrl in MainPage.xaml.cs and run and debug the app.
Set a breakpoint on line 64 for example.

I just tested this and it works.
