### ISSUE TITLE
Logging of Http Request/Response

### ISSUE THREAD

**Issue by spudwebb** [Q42/Q42.HueApi#189]
Is there an easy way to log all the json traffic between the Q42.HueApi and a bridge?

If not, would it be possible to pass an optional HttpMessageHandler to the HttpClient of a HueClient object, so that we can implement logging of requests/responses as explained here:
https://stackoverflow.com/questions/18924996/logging-request-response-messages-when-using-httpclient?answertab=votes#tab-top

?

**Comment by michielpost** [comment]
I created a PR so you can provide your own HttpClient. Will this work for your scenario?
https://github.com/Q42/Q42.HueApi/pull/190

**Comment by spudwebb** [comment]
Yes this will work. thanks

**Comment by michielpost** [comment]
Ok, this is now included in version 3.11.0, available on NuGet: https://www.nuget.org/packages/Q42.HueApi
