### ISSUE TITLE
Notifications for Light or State-Changes?

### ISSUE THREAD

**Issue by AleRoe** [Q42/Q42.HueApi#192]
Hello there!
Is there any means of receiving notfications if a Hue device changes it state or device properties?
I need to know when a Light is turned on or off.
Currently, I continously poll the Lights-collection and look for changes in the device properties by comparing the device with a local cached version. This is of course somewhat inefficient. 
Alternatively it would help if the Light object had a timestamp when its properties last changed.
Any ideas?

Thanks and kind regards
Alexander

**Comment by michielpost** [comment]
Hi Alexander,

Getting push notifications would be great. But the library is limited to what the Hue API offerts. There is currently no push/notification support. So polling it the way to go.

You can contact the Hue team and request this feature.
https://developers.meethue.com/forum/

**Comment by AleRoe** [comment]
Hi Michiel,

okay!
And thanks for your prompt reply!

Cheers
Alexander
