### ISSUE TITLE
SceneCommand not changing scene?

### ISSUE THREAD

**Issue by No0Vad** [Q42/Q42.HueApi#193]
NuGet version: 3.12.0

I noticed that **RecallSceneAsync** or **SceneCommand** does not activate the scene.
I used **GetScenesAsync** to find that the _Relax_ scene has Id **FuPwrV9h-1jyo7x**

But neither of the code below changes the scene:
`await client.RecallSceneAsync("FuPwrV9h-1jyo7x", groupId);`
`await client.SendGroupCommandAsync(new SceneCommand("FuPwrV9h-1jyo7x"), groupId);`

The calls each return a SuccessResult

**Comment by michielpost** [comment]
I had a look at the code and tested the json output but did not notice anything weird.

Make sure to use the groupId that belongs to the scene. So get the scene from the bridge,

```cs
var scenes = await _client.GetScenesAsync();
var scene = scenes.First();

var command = new SceneCommand { Scene = scene.Id };

await _client.SendGroupCommandAsync(command, scene.Group);
```

Can you check the json response from the bridge (for example using Fiddler https://www.telerik.com/fiddler)

**Comment by No0Vad** [comment]
Thanks to your code I've noticed the scenes are duplicated to how many groups you have.
I have 2 groups. The **Relax** Id I first found was to group 2, when I was trying to change the scene on group 1 *facepalm*

![image](https://user-images.githubusercontent.com/9308455/66148155-937fc400-e610-11e9-8e0b-9a23ea6af0b3.png)

When I have the correct group Id everything works as expected.
