### ISSUE TITLE
Schedules and light commands

### ISSUE THREAD

**Issue by BioTurboNick** [Q42/Q42.HueApi#196]
The LightCommands are really easy to use. I want to add them to a schedule, but the Schedule object doesn't seem to consume them. Is there a way to convert it?

**Comment by michielpost** [comment]
Yes, you can combine a LightCommand and a Schedule, see this example:
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi.Tests/ScheduleTests.cs#L73-L75

**Comment by BioTurboNick** [comment]
I see, thank you.
