### ISSUE TITLE
SerializationException when 'alert' state is set to 'null'

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#210]
Apparently, it seems to be possible for the Alert state to be null (no idea how, might be a glitch). If so, the parsing fails with the following error:

> Newtonsoft.Json.JsonSerializationException: 'Cannot convert null value to Q42.HueApi.Alert. Path 'state.alert', line 8, position 17.'

Debug data:

`{
  "manufacturername": "Philips",
  "modelid": "LTW001",
  "uniqueid": "00:00:00:00:00:00:3c:af-0b",
  "type": "Color temperature light",
  "state": {
    "bri": 0,
    "alert": null,
    "reachable": true,
    "on": false,
    "xy": [
      0.157973,
      0.053367
    ],
    "colormode": "ct",
    "ct": 344
  },
  "name": "Light name",
  "swversion": "1.46.13_r26312",
  "config": {
    "direction": "omnidirectional",
    "startup": {
      "configured": false,
      "mode": "safety"
    },
    "archetype": "classicbulb",
    "function": "mixed"
  }
}`

**Comment by michielpost** [comment]
Alert is now nulllable.

**Comment by niels9001** [comment]
@michielpost Cool, thanks! Is this fix included in the latest NuGet package?

**Comment by michielpost** [comment]
No not yet. Will create a new release next week when I have time to look at the other open issues.

**Comment by michielpost** [comment]
Release 3.15.0 is now on NuGet
