### ISSUE TITLE
Support for deCONZ?

### ISSUE THREAD

**Issue by spudwebb** [Q42/Q42.HueApi#224]
deCONZ API and Philips Hue API are very similar:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Hue-API-Compatibility

I found this library that is based on Q42.HueAPI which supports deCONZ
https://github.com/MadMonkey87/InnerCore.Api.DeConz

I'm just wondering if there is any plan to enhance the Q42.HueApi so that it supports both deCONZ and Philips Hue API?

**Comment by michielpost** [comment]
There are no plans to support the deCONZ api. This library only targets the Hue API.
Best option is to use the forked version https://github.com/MadMonkey87/InnerCore.Api.DeConz

**Comment by spudwebb** [comment]
ok thank you for answering
