### ISSUE TITLE
Trying to create a GroupScene and getting exception

### ISSUE THREAD

**Issue by guytaylor** [Q42/Q42.HueApi#227]
Hi there,
I am trying to create a GroupScene and am getting an exception:

![image](https://user-images.githubusercontent.com/34499540/93203096-23be0700-f797-11ea-81df-9edf34ec3f8a.png)

I assumed from the Phillips docs, that would be all I need to pass:
![image](https://user-images.githubusercontent.com/34499540/93203202-5831c300-f797-11ea-8585-80b85f1b3abb.png)

Can you please advise what I am missing?
Thanks :)
Guy

PS. Creating LightScenes like this works fine:
![image](https://user-images.githubusercontent.com/34499540/93203623-148b8900-f798-11ea-97dc-182fbd929a4f.png)

**Comment by michielpost** [comment]
Thanks, that was a bug. Fixed in version 3.15.5, now on NuGet!

**Comment by guytaylor** [comment]
That worked. Thank you very much for the quick fix!! :)
