### ISSUE TITLE
ColorConverter package not in main NuGet package set and not directly linked

### ISSUE THREAD

**Issue by Exergist** [Q42/Q42.HueApi#235]
The ReadMe refers to the ColorConverter functionality and the ["Wrong RGB" issue](https://github.com/Q42/Q42.HueApi/issues/70) mentions that the ColorConverter is in a separate package. 

I just wanted to mention (in case this wasn't intentional) that the ColorConverter is not part of the main NuGet package set for Q42.HueAPI as of 3.15.8. 

If this IS intentional, then I suggest a link to the ColorConverter NuGet package be added to the ReadMe.

**Comment by michielpost** [comment]
It's mentioned in the readme, I made it a little more clear.

**Comment by Exergist** [comment]
Why not just link directly to the NuGet site for the ColorConverters?

> The[ Q42.HueApi.ColorConverters NuGet package](https://www.nuget.org/packages/Q42.HueApi.ColorConverters/) contains

or 

> The Q42.HueApi.ColorConverters NuGet package ([download directly from NuGet](https://www.nuget.org/packages/Q42.HueApi.ColorConverters/)) contains:

Maybe I'm the dim bulb in the room, but initially it wasn't obvious to me that I had to go find it myself since the rest of the project's NuGet files are directly linked.
