### ISSUE TITLE
Wiz Support

### ISSUE THREAD

**Issue by isaacrlevin** [Q42/Q42.HueApi#245]
I noticed that there is no real NuGet package for Phillips Wiz, which is a hub-less light that Phillips sells. The light discovery is IP based and it seems the light configuration is very similar to Hue. Would you be interested in a pull request to support Wiz if I can make it work?

**Comment by michielpost** [comment]
I didn't know about Philips Wiz, and I don't have access to any Philips Wiz hardware. If it's included in this project, people will come to me for support, questions, bugs etc and I won't be able to help them.
So it's best to create a new seperate project and NuGet package that targets the Philips Wiz products.
I'll be happy to include a link to your project.
