### ISSUE TITLE
Add light to EntertainmentGroup en re-activate streaming

### ISSUE THREAD

**Issue by TripleNico** [Q42/Q42.HueApi#253]
Hi Mark,

Today i created a function where a user can add or remove a light to a Entertainmentgroup using `UpdateGroupAsync` . After the call i noticed than the bridge stops streaming. So i think that we have to setup the Entertainment again? Or is there a simple call like `UpdateStreamingGroup` ?

**Comment by michielpost** [comment]
There's no special call to update a streaming group while it's streaming. If the bridge stops streaming while you update the group, it's best to restart streaming manually.

**Comment by TripleNico** [comment]
hi @michielpost thanks for your swift reply. Alright if the bridge stops streaming what would be the "correct" way to recover this? Is that by doing the same steps as noted here: https://github.com/Q42/Q42.HueApi/blob/master/EntertainmentApi.md#connect-to-an-entertainment-group or is there an simpler way?

**Comment by michielpost** [comment]
Yes, safest thing is to follow these steps to setup a new fresh connection.

Calling `var entGroup = new StreamingGroup(group.Locations);` needs all light locations. So it's important to have up to date group info when you just added a new light to the group.

Normally, if the connection is lost you might be able to reconnect with this:
```
client.Close()
await client.Connect(group.Id);
client.AutoUpdate(entGroup, 50);
```
But creating a new client is safer, that way you're sure all internal state is reset.

**Comment by TripleNico** [comment]
Alright i will do some testing to see what the best result is in our case.

Another question, if a light is added to an entertainment group should a location be also set? Or is it just add, re-init streaming and done?

**Comment by michielpost** [comment]
A location is needed for effects that use it. For location aware effects, like a moving light from left to right.
If it's not set, the location is probably 0,0, so that might not be what you want.

**Comment by TripleNico** [comment]
Today i had some times to dive into this and it seems i'm stuck in a loop. Let me explain:

I setup Entertainment with the code:
```C#
//Initialize streaming client
StreamingHueClient client = new StreamingHueClient(ip, key, entertainmentKey);

//Get the entertainment group
var all = await client.LocalHueClient.GetEntertainmentGroups();
var group = all.FirstOrDefault();

//Create a streaming group
var entGroup = new StreamingGroup(group.Locations);

//Connect to the streaming group
await client.Connect(group.Id);

//Start auto updating this entertainment group
client.AutoUpdate(entGroup, 50);
```

Then if you open the Hue app on your Phone you will see that streaming is active. So far so good.

In the background i have a Task that polls every X seconds to check if `HueBridgeConfig.IsStreamingActive` is still active. If not it will try an restore the streaming. For that i tried several options but let's start with this:
```C#
//Get the entertainment group
var all = await client.LocalHueClient.GetEntertainmentGroups();
var group = all.FirstOrDefault();

//Create a streaming group
var entGroup = new StreamingGroup(group.Locations);

//Connect to the streaming group
await client.Connect(group.Id);

//Start auto updating this entertainment group
client.AutoUpdate(entGroup, 50);
```
Now in the Hue app on your Phone click "STOP streaming", the poll task will kick in and fires above code. This results in Streaming Mode being activated again(Yeah!) but after a short time Streaming stops again and i don't know why. Resulting in the poll task kicking in and reconnect, etc.. etc..

I also tried only this single line, with the same result.
```C#
 var enableResult = await _localHueClient.SetStreamingAsync(groupId);
```

The only thing i haven't tried yet is also creating a new instance of `New StreamingHueClient` but it seams a bit unnecessary to re-active a stopped StreamingGroup...

Any tips?

**Comment by TripleNico** [comment]
It seems that i have got this working now, and this is the code for it:

```vb.net
Class MainWindow

    Private entLayer As EntertainmentLayer

    Private Async Sub Button_Click(sender As Object, e As RoutedEventArgs)

        'Register app with the bridge
        Dim streamClientKey As RegisterEntertainmentResult = Await New LocalHueClient("192.168.70.60").RegisterAsync("MyApp", "MyDevice", True)

        'Initialize streaming client
        Dim client As New StreamingHueClient(streamClientKey.Ip, streamClientKey.Username, streamClientKey.StreamingClientKey)

        'Get the entertainment group
        Dim all As IReadOnlyList(Of Group) = Await client.LocalHueClient.GetEntertainmentGroups()
        Dim group As Group = all.FirstOrDefault()

        'Create a streaming group
        Dim entGroup As New StreamingGroup(group.Locations)

        'Connect to the streaming group
        Await client.Connect(group.Id)

        'Start auto updating this entertainment group
        Dim SetAndForgetTask As Task = client.AutoUpdate(entGroup, CancellationToken.None, 50)

        'Create new base layer
        entLayer = entGroup.GetNewLayer(True)
        entLayer.SetBrightness(CancellationToken.None, 1)

        'Setup Watchdog for streaming with auto recovery
        Await Task.Run(Async Function()

                           Do While True

                               Dim LocalHueBridge As Bridge = Await client.LocalHueClient.GetBridgeAsync

                               If LocalHueBridge.IsStreamingActive Then
                                   Console.WriteLine("Streaming is still active....")

                                   'Loop through RGB to show it works
                                   entLayer.SetColor(CancellationToken.None, New RGBColor("FF0000")) 'Set Red
                                   Await Task.Delay(500)
                                   entLayer.SetColor(CancellationToken.None, New RGBColor("00FF00")) 'Set Green
                                   Await Task.Delay(500)
                                   entLayer.SetColor(CancellationToken.None, New RGBColor("0000FF")) 'Set Blue

                               Else
                                   Console.WriteLine("Streaming stopped, Re-enable Streaming ...")

                                   'First we have to close the current socket and setup a new one:
                                   client.Close()

                                   'Now create new StreamingClient
                                   client = New StreamingHueClient(streamClientKey.Ip, streamClientKey.Username, streamClientKey.StreamingClientKey)

                                   'Connect to the streaming group
                                   Await client.Connect(group.Id)

                                   'Start auto updating this entertainment group
                                   SetAndForgetTask = client.AutoUpdate(entGroup, CancellationToken.None, 50)
                               End If

                               Await Task.Delay(2500)
                           Loop

                           Return True
                       End Function)
    End Sub
End Class
```
