### ISSUE TITLE
Creating an entertainment Zone from Q42

### ISSUE THREAD

**Issue by Christanoid** [Q42/Q42.HueApi#258]
Hi,

I am working on a multi room effect / animation lighting application that has it's own knowledge of rooms and positions.
Considering that I need to be able to on the fly create and delete Entertainment zones on my Hue bridge as needed in my current situation. 

I cannot find any way in the library to create or remove entertainment zones.
Is there any way to do this form Q42 or do I have to implement my own HTTP communication with the Hue bridge to do this sort of management.

Thanks for the help,
Chris

**Comment by Christanoid** [comment]
Nevermind this.

In case anyone else has this problem in the Future:

I was searching for something along the lines of "CreateEntertainmentZone". The real function you have to use is:
"client.LocalHueClient.CreateGroupAsync"

**Comment by michielpost** [comment]
Also check out https://github.com/michielpost/HueLightDJ for an example with multiple bridges, multiple zones animation system.
