### ISSUE TITLE
Inconsistent use of Async in method names between the original API and Clip V2

### ISSUE THREAD

**Issue by PonchoPowers** [Q42/Q42.HueApi#280]
In the original API, async methods were postfixed with **Async** like so:
GetSensorsAsync

In the Clip V2 API, they aren't.

There are several mentions to this standard convention mentioned in the Microsoft Docs:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model

It is a widely accepted convention too that async methods are postfixed with **Async**.

Was there a reason for breaking from convention and would you accept a PR that renames all async methods in Clip V2 to include **Async** at the end of the method name?

**Comment by michielpost** [comment]
Yes, good point. Will update the names in a next version.
