### ISSUE TITLE
Not working from Visual Studio 2015

### ISSUE THREAD

**Issue by KellyMurphy** [Q42/Q42.HueApi#39]
I tried to add this to a windows forms project in visual studio 2015 using nuget and it would not install correctly.  

I was able to install it using a project created in VS2013.  Once I opened the Solution in VS2015 it worked fine.

**Comment by michielpost** [comment]
Thanks. Fixed in this commit: https://github.com/Q42/Q42.HueApi/commit/1acbbc15adfa6447cd646682d46e05cd8d7713d0

New packages are on NuGet. If you try to install Q42.HueApi version 1.9.3.42 in a Windows Forms app, it will work.
