### ISSUE TITLE
System.Net.HttpRequestexception with RegisterAsync 

### ISSUE THREAD

**Issue by alamata** [Q42/Q42.HueApi#41]
hey ,...

sorry for this,...

i have a test application in c# in VS 2013

            HueClient client = new HueClient("192.168.0.6");
            var appKey = await client.RegisterAsync("homidomhue", "homidomserveur");

i have use this nuget command "" Install-Package Q42.HueApi "" so use the 1.10.0.42 version
i have updated the firmware of the bridge

but i have an ""System.Net.HttpRequestexception ""error when i try to register my app in the hue bridge

Exception:Levée : "Le serveur a commis une violation de protocole. Section=ResponseHeader Detail=CR doit être suivi par LF" (System.Net.WebException)
Une System.Net.WebException a été levée : "Le serveur a commis une violation de protocole. Section=ResponseHeader Detail=CR doit être suivi par LF"

what i have done wrong,....??

thx for in advance for  your help,...

**Comment by michielpost** [comment]
Can you maybe put a proxy like fiddler in between and see if the bridge gives a response? And if the request is correct?

**Comment by alamata** [comment]
hey ,...

thx for your intervention,...
i have try serveral times in the day ,...with the same error,...

i just install fiddler,...

waiting the response,... and i have had an appkey...  
but not each time,... oops

----  with no fiddler launched
       i have now this error ""TargetInvocationException""

----  with fiddler  launched  
        i have an appkey,....

dont undersatnd what's happens

is it possible that comes from my personnal network issues

**Comment by alamata** [comment]
Hey,...

Here is the situation,...

--- i have a machine with kaspersky internet suite
>>with fiddler the request and the response are ok ( i have receive an appkey)
>>whith no fiddler launched i have an error
>> when kis is desactived everything is ok 

--- i have tested on another machine with no kasperky internet suite
>> everyhting is ok (request and response) with no fiddler installed

so the trouble come from kasperky internet suite

What are the settings to change in kis to have this running normally

thx for your patience,...

**Comment by alamata** [comment]
i have a solution with kis it s certainly not perfect for the security 
but it works  for the RegisterAsync function,...

kis
configuration
advanced settings
network
control only the selectionned ports
and for the port 80 set on desactivated



![kissettings](https://cloud.githubusercontent.com/assets/554318/10273206/17c87f12-6b2d-11e5-9ef0-64d1c0c817ba.png)


if you have another solution,...

**Comment by michielpost** [comment]
Thanks for reporting!
You should maybe contact kaspersky and ask why they are blocking this request.
