### ISSUE TITLE
Setting transitiontime on a scene

### ISSUE THREAD

**Issue by dmarjoram** [Q42/Q42.HueApi#44]
Having a problem setting transition time on a scene with API 1.11

	LightCommand transition = new LightCommand() { TransitionTime = TimeSpan.FromSeconds(2) };
	hueClient.ModifySceneAsync("bcbfb5af0-on-0", "0", transition);

Gives error result:

Q42.HueApi.Models.Groups.ErrorResult 
Type: 3 
Address: /scenes/bcbfb5af0-on-0/lights/bcbfb5af0-on-0 
Description: resource, /scenes/bcbfb5af0-on-0/lights/bcbfb5af0-on-0, not available 

Thanks

**Comment by michielpost** [comment]
Yes, this is probably caused by changes in the Bridge API with version 1.11 that was released this week. The scenes endpoint has changed from /state to /lightstate
I'm working on an update to support the new bridge version.

**Comment by michielpost** [comment]
Q42.HueApi version 2.1.0 is now on NuGet. Please check if this fixes the error for you.

**Comment by dmarjoram** [comment]
Hi there,

Thanks for the quick update. I can confirm that the scenes are now being updated with the current lightstate, however I can't set a scene transition time via the Q42 API. This used to be in LightCommand but I now see in the Hue API doc that you can provide this when updating a scene. 

I've managed to get the desired outcome but sending a raw command with the fiddler composer. There seems no way to include the transitiontime property with UpdateSceneAsync at present.

It seems that transitiontime an additional property (the only one?) that can be added when you provide storelightstate, according to "If set, the lightstates of the lights in the scene will be overwritten by the current state of the lights. Can also be used in combination with transitiontime to update the transition time of a scene."

![transitiontime](https://cloud.githubusercontent.com/assets/12830675/11725551/35288132-9f72-11e5-9afa-d1be31b36b62.PNG)

Thanks again.

**Comment by michielpost** [comment]
Ah yes, that's a little bit hidden in the documentation.
I added transitiontime, you can download the new 2.1.1 release from NuGet

**Comment by dmarjoram** [comment]
Almost works! The transitiontime property is serialized to 1 decimal place, so TimeSpan.FromSeconds(4) becomes 40.0 in the JSON. When sent to the bridge you get a null result back and the transition is not effective.

Changing the value to 40 directly in the request, and not 40.0, resolves the issue and the transition works as intended.

Thanks

**Comment by dmarjoram** [comment]
Have created pull request with simple fix

Kind Regards,
Darrell

**Comment by michielpost** [comment]
Thanks! New version is up on NuGet
