### ISSUE TITLE
With the last update (= merge), colors are no longer correct for every ModelID

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#47]
Since the last merge (removing some of the color conversion code) not all colors are correct anymore. The code was based on the official Obj-C code that Philips uses (http://www.developers.meethue.com/documentation/color-conversions-rgb-xy) in its official iOS and Android apps.

With the last commit, colors seem fine for the normal bulbs, but colors are off for the LightStrip. Red is now yellow etc. - before this was all correct.

Can this be undone? Or can the possibility be added to add a custom converter if you do not wish to support this into this API (optional)?

Niels

**Comment by michielpost** [comment]
Thanks for the feedback. Maybe @patrickmeiring knows what causes this?

An alternative would be to move the color converters to separate packages so everybody can use the one they like.

**Comment by niels9001** [comment]
Would be nice - I just checked, it's happening with the 'normal' bulbs as well. Before the change the right RGB colors from the WriteableBitmap were translated to the right Hue colors - now they seem off (e.g. yellowish-white instead of white-white or light-green instead of dark blue).

Let me know if there's anything to test, I'd be happy to test it (strip and bulbs). Keep up the great work!

**Comment by patrickmeiring** [comment]
Just investigating this now, @niels9001 . Which method are you calling to set bulb colours?
If its LightCommand.SetColor(LightCommand lightCommand, RGBColor color, string model), are your ranges for red, green and blue between 0.0-1.0 or 0-255?

It's quite possible I broke this in the last update. (The correct is now between 0.0 and 1.0).

The conversion that's going on should be very close to what is described in http://www.developers.meethue.com/documentation/color-conversions-rgb-xy (it's the same transformation matrices and everything).

**Comment by niels9001** [comment]
I'm using the following: 

  SendLightCommand(new LightCommand().SetColor(new RGBColor((double)ColorPicker.SelectedColor.R, (double)ColorPicker.SelectedColor.G, (double)ColorPicker.SelectedColor.B), ((Light)SelectedDevice).Id));

After changing it to:

      SendLightCommand(new LightCommand().SetColor(new RGBColor(((double)ColorPicker.SelectedColor.R / 255), ((double)ColorPicker.SelectedColor.G / 255), ((double)ColorPicker.SelectedColor.B) / 255), ((Light)SelectedDevice).Id));

It works better. I think most of the colors are now correct, although I feel white is still a bit yellow-ish.

**Comment by patrickmeiring** [comment]
@niels9001 Phew, good to hear that much is working!

When you say white, which RGB color are you passing in? Is it #FFFFFF (i.e. R: 1.0, G: 1.0, B: 1.0)?
If the code is working as designed, it should give you (x,y) coordinates of (0.32273, 0.32902).

This is calculated from the Philips-supplied matrix:
            double X = r * 0.664511f + g * 0.154324f + b * 0.162028f;
            double Y = r * 0.283881f + g * 0.668433f + b * 0.047685f;
            double Z = r * 0.000088f + g * 0.072310f + b * 0.986039f;
Substituting (r = 1.0, g = 1.0, b = 1.0), you get (X = 0.980903, Y = 0.999999, Z = 1.058437)
converting to xy coordinates by dividing X,Y by (0.980903 + 0.999999 + 1.058437), 
you have (0.32273, 0.32902).

I'm using the following code to test
```C#
 static async void TestColors()
        {
            //HttpBridgeLocator locator = new Q42.HueApi.HttpBridgeLocator();
            //var ips = await locator.LocateBridgesAsync(TimeSpan.FromSeconds(10));

            //await client.RegisterAsync();

            LocalHueClient client = new Q42.HueApi.LocalHueClient("<Bridge IP>", "<Token>");
            LightCommand command = new LightCommand();

            command.SetColor(255, 255, 255, "LCT001"); // White
            command.TurnOn();

            await client.SendCommandAsync(command);
        }
```

**Comment by niels9001** [comment]
I'm getting the colors dynamically from images (with a colorpicker), so it could be that the color is not #FFF but something close (although it looks white to the user) and this results in yellow-ish white.

Niels

**Comment by patrickmeiring** [comment]
(If it's possible to describe) how yellowy-white are we talking about? Is there a change you could put in 
a breakpoint and extract the RGB values you think correspond to a yellowy white? 

Otherwise, I might still have a look tomorrow (it's late in Australia).

I'm relatively confident the calculations are being performed correctly -- there's a bunch of unit tests in place that check the conversion from xy -> RGB -> xy is consistent, and one that generates these pretty Gamut charts: http://imgur.com/a/rniqL for manual checking.

Patrick

**Comment by patrickmeiring** [comment]
To double-check check everything is working, I wrote a method that exercises the RgbToXY() method with arbitrary RGB colors and plots the resulting xy points on a chart. 

```C#

        private Bitmap PlotRgbColorsOnXy(string model)
        {
            int dimension = 500;
            Bitmap bitmap = new Bitmap(dimension, dimension);
            for (int x = 0; x < dimension; x++)
                for (int y = 0; y < dimension; y++)
                {
                    bitmap.SetPixel(x, y, Color.Black);
                }

            // Run from 255 -> 0 so that we see any defects with converting very dim colors
            for (int r = 255; r >= 0; r -= 1)
                for (int g = 255; g >= 0; g -= 1)
                    for (int b = 255; b >= 0; b -= 1)
                    {
                        if (r == 0 && g == 0 && b == 0) continue;

                        var rgbColor = new RGBColor(r / 255.0, g / 255.0, b / 255.0);
                        var xy = HueColorConverter.RgbToXY(rgbColor, model);

                        int x = (int)(xy.x * dimension);
                        int y = (int)(xy.y * dimension);

                        // CIE1931 charts are drawn with y-increasing being upwards, not downwards as in bitmaps.
                        bitmap.SetPixel(x, (dimension - 1) - y, Brighten(rgbColor));
                    }

            return bitmap;
        }

        private Color Brighten(RGBColor color)
        {
            // Convert from pixel outputs to linear color components.
            double red = InverseGamma(color.R);
            double green = InverseGamma(color.G);
            double blue = InverseGamma(color.B);

            // Normalise so the largest component has a value of 1.0
            // Then re-apply gamma.
            double max = Math.Max(red, Math.Max(green, blue));
            red = Gamma(red / max);
            green = Gamma(green / max);
            blue = Gamma(blue / max);

            return Color.FromArgb((int)(red * 255.99), (int)(green * 255.99), (int)(blue * 255.99));
        }

```

You can see the charts below. There's a few small artifacts at the corners because the red, green and blue primaries assumed in Philips' RGB<->XY transformations cannot produce all the colors all the bulbs support. (See the white triangle in the chart here: http://imgur.com/zelKnSk )

![gamuta_inverse](https://cloud.githubusercontent.com/assets/4349787/12220090/3afe1530-b7ab-11e5-8dcb-66ccca91bd3a.png)
![gamutb_inverse](https://cloud.githubusercontent.com/assets/4349787/12220089/3af77cd4-b7ab-11e5-856c-6f359c856790.png)
![gamutc_inverse](https://cloud.githubusercontent.com/assets/4349787/12220091/3b02be5a-b7ab-11e5-98b4-ae0720572701.png)

**Comment by michielpost** [comment]
Is this still an issue, or is everything ok now?

**Comment by niels9001** [comment]
The last tip did the trick (dividing / 100). Can be closed now. Thanks!
