### ISSUE TITLE
(enhancement request): more versatile schedule command parsing?

### ISSUE THREAD

**Issue by stefjan** [Q42/Q42.HueApi#48]
Hi,

the "waking up" scenario which can be found here: http://labs.meethue.com/ relies on other "sensors" and has a schedule item which is not a SceneCommand nor a LightCommand. It actually looks like this:

```
{
	"1": {
		"name": "waking-uphuelabs-abc",
		"description": "HueLabs schedule-huelabs-abc",
		"command": {
			"address": "/api/<id>/sensors/9/state",
			"body": {
				"status": 1
			},
			"method": "PUT"
		},
		"localtime": "W003/T09:15:00",
		"time": "W003/T08:15:00",
		"created": "2016-01-02T22:12:38",
		"status": "enabled"
	}
}
```

i did not look further into it yet, but the rules of the cited example also use actions which are not Scene or LightCommands, so the same issue might pop-up there.

Are there any plans to support these types of commands or would that lead this project to far?

kind regards
stefan

**Comment by michielpost** [comment]
Thanks for letting me know. This projects aims to support all interaction with the Bridge API. So I'd also like to support this scenario.

I made a GenericScheduleCommand that basically just supports raw json for a command body.
Usage example is here:
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi.Tests/ScheduleTests.cs#L87-L92

So writing this value to the bridge can now be done. But I haven't figured out yet how to properly read the values back when getting a list of all schedules from the bridge. There's a CommandBodyConverter that reads the value and looks for a Scene property, then assumes it's a SceneCommand and all else is a LightCommand.

https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/Converters/CommandBodyConverter.cs#L27-L41

I don't know how to differentiate between a LightCommand and this new GenericCommand. One option is to treat all commands as GenericCommands when reading them from the bridge. Or look at the address the command is posting to. But I don't have that information inside the CommandBodyConverter.

So not really sure yet. Any thoughts?

**Comment by stefjan** [comment]
thanks, i will give the GenericCommand a try on monday, It will definitely let me achieve what i want to do.

Reading back from the bridge is nice but maybe not that crucial: the GenericCommands will always be very specific so making the Q42.HueApi more complex is maybe not worthwhile

i had a look at the sensor datafields mentioned at http://www.developers.meethue.com/documentation/supported-sensors and there is nothing unique which sets them apart from lights. So the address seems to be the unique identifier (which also means i can't help you out).

i assume the fields in the class SensorState (in Sensor.cs) are the state attributes of the sensors (as mentioned on http://www.developers.meethue.com/documentation/supported-sensors)? In that case these ones might be missing: 
```
bool open	
int32 temperature	
int32 humidity	
bool flag	
```

**Comment by michielpost** [comment]
Thanks, I've added the extra Sensor State fields

**Comment by stefjan** [comment]
i tried a schedule and a rule, both work fine using the GenericCommand.

Regarding the read-back: i am not a SW developer, so maybe it's a bad idea/technique/... (and it does not look that clean) but i had a look at the newtonsoft.json documentation and there is a OnDeserialized callback method: http://www.newtonsoft.com/json/help/html/SerializationCallbackAttributes.htm, 

Adding that to the InternalBridgeCommand gives me access to the Address and Body after the deserialisation. So if i defer the deserialisation of Body (and i simply return a GenericScheduleCommand in the ReadJson of the CommandBodyConvertor) then i can check the Address in the OnDeserializedMethod and JsonConvert.DeserializeObject of the Body to the relevant type and return that as Body.

the additional reasoning behind this is that i got the idea that the actions (for the rules) and commands (for the schedules) are maybe not that generic: it's only allowed to change the supported fields of the (supported) sensors, so it is feasible to define a SensorCommand (which covers all fields of all possible sensors) and keep GenericCommand as a fall-back, but use SensorCommand to control the sensors.

just my 2cents, not sure it's a good idea and maybe it's even totally wrong (and only works by accident - as said, i don't do SW for a living).

and some code i copy-pasted together to make the above text a bit clearer:

internalbridgecommand.cs
```
    
    [OnDeserialized]
    internal void OnDeserializedMethod(StreamingContext context)
    {
        // need to add more tests i guess ... but to start with:
        if (Address.Contains("sensor")) {
            var tmp = Body as GenericScheduleCommand;
            // this is fake, but i did not want to spend time on building a sensorcommand class yet
            // in real life this should not be a scenecommand            
            var returnvalue = new SceneCommand(); 
            returnvalue = JsonConvert.DeserializeObject<SceneCommand>(tmp.JsonString);
            returnvalue.Scene = "999";
            Body = returnvalue;
        }
        else
        {
            var tmp = Body as GenericScheduleCommand;
            var returnvalue = new LightCommand();
            returnvalue = JsonConvert.DeserializeObject<LightCommand>(tmp.JsonString);
            Body = returnvalue;
        }
    }
```

commandbodyconvertor:
```
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
      if (reader.TokenType == JsonToken.StartObject)
      {
        JObject jObject = JObject.Load(reader);

        return new GenericScheduleCommand(jObject.ToString());
       }
    }
```

**Comment by michielpost** [comment]
Great suggestion. I was just in the middle of creating something in this direction. I've added the OnDeserializedMethod. When reading Schedules from the bridge, by default all commands are GenericScheduleCommands. But the OnDeserializedMethod tries to create a Scene, Light or SensorCommand.

Seems to work great.

Only thing is, what properties are supported for a SensorCommand? All the Sensor State properties?

**Comment by michielpost** [comment]
All these changed are now released with version 2.2.1 which is up on NuGet

**Comment by stefjan** [comment]
i was also just wondering what to put in the sensorcommand.

here http://www.developers.meethue.com/documentation/message-structure-and-response-0 they mention
```
R         Returned by GET
RO      Resource might not support attribute
W         Required for PUT
WO      Optional for PUT
C         Required for POST
CO      Optional for POST
```
since post only seems to be used to find and create new sensors, those fields probably do not matter, so that leaves all "W" and "WO" fields (update sensor + change config + change state). So i was thinking to add those.(most of them are common anyhow)

**Comment by stefjan** [comment]
just retrieved 2.2.1 from NuGet and it works nicely (using the 2 visual tests i have for the moment :-/ 

Feel free to close this issue.

thanks, great job!

**Comment by michielpost** [comment]
Nice list on the Philips documentation site, R, RO, W, CO etc. But where can I find these codes in the documentation?

It looks like the codes are not used anywhere in the Philips documentation. Only required and optional. Or am I missing something?

**Comment by stefjan** [comment]
the codes are only used on the supported sensors page: http://www.developers.meethue.com/documentation/supported-sensors

so i was thinking about doing something like this:
```
	/// <summary>
	/// Sends a SensorCommand
	/// </summary>
	[DataContract]
	public class SensorCommand : ICommandBody
	{
		
        // from General Sensor Resource
        // The human readable name of the sensor, can be changed by the user. Is not allowed to be empty on change.
        [DataMember (Name = "name")]
        public string? Name { get; set; }
        // config object attributes
        // Turns the sensor on/off. When off, state changes of the sensor are not reflected in the sensor resource. Default is “true”
        [DataMember (Name = "on")]
        public bool? On { get; set;}
        // The current battery state in percent, only for battery powered devices. Not present when not provided on creation or modification (CLIP sensors).
        [DataMember (Name = "battery")]
        public int? Battery{ get; set; }
        // Optional URL of the CLIP sensor. Not present when not provided on creation or modification.
        [DataMember(Name = "url")]
        public string? Url { get; set; }
        // state object attributes
        // nothing

        // from CLIP Generic Status Sensor
        // already covered: on, battery, url
        // Sensor specific state attributes (you already had that one, just moved it here)
        [DataMember(Name = "status")]
        public int? Status { get; set; }

        // from CLIP Generic Flag Sensor
        // already covered: on, battery, url
        // Sensor specific state attributes
        [DataMember(Name="flag")]
        public bool? Flag { get; set; }

        // from Daylight Sensor
        // already covered: on
        // Supported config attributes
        // GPS coordinate longitude in decimal degrees DDD.DDDD{W|E} with leading zeros required ending with W or E e.g. 000.3295W “none” .  In future versions this may change to null.
        [DataMember(Name = "long")]
        public string? Longitude { get; set; }
        // GPS coordinate latitude in decimal degrees DDD.DDDD{N|S} with leading zeros required e.g. 010.5186N ending with N or S “none”.In future versions this may change to null.
        [DataMember(Name = "lat")]
        public string? Lattitude { get; set; }
        // Timeoffset in minutes to sunrise
        [DataMember(Name = "sunriseoffset")]
        public int? SunriseOffset { get; set; }
        // Timeoffset in minutes to sunset.
        [DataMember(Name = "sunsetoffset")]
        public int? SunsetOffset { get; set; }

        // from CLIP Humidity
        // already covered: on, battery, url
        // Sensor specific state attributes
        // Current humidity 0.01% steps (e.g. 2000 is 20%)
        [DataMember(Name = "humidity")]
        public int? Humidity { get; set; }

        // from CLIP Temperature
        // already covered: on, battery, url
        // Sensor specific state attributes
        // Current temperature in 0.01 degrees Celsius
        [DataMember(Name = "temperature")]
        public int? Temperature { get; set; }

        // from CLIP Presence
        // already covered: on, battery, url
        // Sensor specific state attributes
        // True if sensor detects presence
        [DataMember(Name = "presence")]
        public bool? Presence { get; set; }

        // from CLIP OpenClose
        // already covered: on, battery, url
        // Sensor specific state attributes
        // True if switch is currently open
        [DataMember(Name = "open")]
        public bool? Open { get; set; }

        // CLIP Switch
        // nothing

        // ZLL Switch
        // already covered: name on, battery, reachable

        // ZGP Switch
        // already covered: name, on

    }
```
(and i am not using my normal editor/pc at this moment, so there could be errors in the above code)

personally i only need State (which you already provided), and i did not check whether the other sensortype (humidity etc) actually exist (as in "can be bought and comply to this scheme"), but at this moment i think the above thing might be a sensible starting point.

**Comment by michielpost** [comment]
I've added these extra properties. They'll come in the next NuGet release.

Closing this issue now. Thanks a lot for your help!
