### ISSUE TITLE
UpdateSceneAsync(string ID, Scene Scene) returns error

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#49]
When calling above function an error is returned. Looking at the JSON with Fiddler:

The above JSON:

{"Id":"F0b-WGcJnehh0Xw","name":"Test","lights":["3","4","6","9"],"owner":"2df02300395f826f244b97502a92ba5f","appdata":{"version":1,"data":""},"picture":"","recycle":true,"locked":false,"version":2,"lastupdated":"2015-12-29T23:29:47","transitiontime":0}

Result:

[{"error":{"type":6,"address":"/scenes/F0b-WGcJnehh0Xw/Id","description":"parameter, Id, not available"}},{"error":{"type":8,"address":"/scenes/F0b-WGcJnehh0Xw/owner","description":"parameter, owner, is not modifiable"}},{"error":{"type":8,"address":"/scenes/F0b-WGcJnehh0Xw/recycle","description":"parameter, recycle, is not modifiable"}},{"error":{"type":8,"address":"/scenes/F0b-WGcJnehh0Xw/locked","description":"parameter, locked, is not modifiable"}},{"error":{"type":6,"address":"/scenes/F0b-WGcJnehh0Xw/version","description":"parameter, version, not available"}},{"error":{"type":6,"address":"/scenes/F0b-WGcJnehh0Xw/lastupdated","description":"parameter, lastupdated, not available"}}]

Turns out Id, Owner, Recycle, Locked, Version, LastUpdated should be ignored.

**Comment by michielpost** [comment]
Fixed in version 2.2.1 which is up on NuGet.
