### ISSUE TITLE
Id is null for groups

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#51]
Very similiar to the bug that was fixed in package 2.0.3: the Id is set to null once it gets saved to cache. This was solved for Scene and Light but still occurs for Group.

private StorageHelper<IReadOnlyCollection<Group>> GroupsHelper = new StorageHelper<IReadOnlyCollection<Group>>(Windows.Storage.ApplicationData.Current.LocalCacheFolder);
 
IReadOnlyCollection<Group> Groups = await hueClient.GetGroupsAsync();
await GroupsHelper .SaveAsync(Groups , "Groups ");
 
 
Get from cache:
IReadOnlyCollection<Group> CachedGroups = await GroupsHelper.LoadAsync("Groups ");

After this, most properties are still there, but Id is set to null.

**Comment by michielpost** [comment]
Group.Id was missing the [DataMember] attribute. Fixed now in version 2.2.3
