### ISSUE TITLE
missing colormode in action fields groups

### ISSUE THREAD

**Issue by stefjan** [Q42/Q42.HueApi#53]
HI,

i noticed that when parsing the group info from the bridge the colormode field is not present. section 2.1.3 in http://www.developers.meethue.com/documentation/groups-api shows an example.

In "2.3.2. Response" at the same page the table mentions:
``` 
| action | object | The light state of one of the lamps in the group.|
```
so ... should/can the field "LightCommand Action" in the Groups.cs be replaced by "State Action"?

kind regards
stefan

**Comment by michielpost** [comment]
Yes, you're correct. I modified the Action property to the type State instead of LightCommand.
Will be updated with the next release.
