### ISSUE TITLE
Light color to RGB

### ISSUE THREAD

**Issue by mphacker** [Q42/Q42.HueApi#54]
Would it be possible to add an ability to get the current color of a light in RGB since there is an ability to set the color using RGB?

**Comment by michielpost** [comment]
You can convert from XY coordinates to RGB like this:
var xy = light.State.ColorCoordinates;
var rgb = HueColorConverter.XYToRgb(new CIE1931Point(xy[0], xy[1]), light.ModelId);

**Comment by mphacker** [comment]
HueColorConverter is not accessible due to it's protection level.

**Comment by michielpost** [comment]
Fixed it. Version 2.2.4 is now on NuGet.

You can use:
`var rgb = light.State.ToRgb();`
