### ISSUE TITLE
Cannot convert null value to Q42.HueApi.Effect. Path '[2].action.effect

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#55]
Although these are not official Hue-compatible lights, GE Lights might trigger the following error:

> Cannot convert null value to Q42.HueApi.Effect. Path '[2].action.effect', line 1, position 627 at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(Json.JsonReader reader, Type objectType, Object existingValue, Json.JsonSerializer serializer)

Bridge JSON related to the lights:

`{"lights":{"1":{"state": {"on":true,"bri":40,"hue":50681,"sat":235,"effect":"none","xy":[0.2742,0.1158],"ct":153,"alert":"none","colormode":"xy","reachable":true}, "type": "Extended color light", "name": "Light1", "modelid": "LCT002", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:d5:10:cc-0b", "swversion": "66013452"},"2":{"state": {"on":true,"bri":41,"hue":41826,"sat":216,"effect":"none","xy":[0.2494,0.1901],"ct":153,"alert":"none","colormode":"xy","reachable":true}, "type": "Extended color light", "name": "Light2", "modelid": "LCT002", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:ea:92:38-0b", "swversion": "66013452"},"3":{"state": {"on":false,"bri":1,"hue":34495,"sat":232,"effect":"none","xy":[0.3151,0.3251],"ct":155,"alert":"lselect","colormode":"hs","reachable":true}, "type": "Extended color light", "name": "Light3", "modelid": "LCT002", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:d1:76:75-0b", "swversion": "66013452"},"4":{"state": {"on":false,"bri":1,"alert":"lselect","reachable":true}, "type": "Dimmable light", "name": "Front porch", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:0b:97:c4-01", "swversion": "1197632"},"5":{"state": {"on":false,"bri":1,"alert":"none","reachable":true}, "type": "Dimmable light", "name": "GELight1", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:10:dd:43-01", "swversion": "1197632"},"6":{"state": {"on":false,"bri":1,"alert":"none","reachable":true}, "type": "Dimmable light", "name": "GELight2", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:0c:06:b6-01", "swversion": "1197632"},"7":{"state": {"on":false,"bri":26,"alert":"none","reachable":true}, "type": "Dimmable light", "name": "GELight3", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:12:5e:7d-01", "swversion": "1197632"},"8":{"state": {"on":false,"bri":1,"alert":"lselect","reachable":true}, "type": "Dimmable light", "name": "GELight4", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:13:2a:ec-01", "swversion": "1197632"},"9":{"state": {"on":false,"bri":22,"alert":"none","reachable":true}, "type": "Dimmable light", "name": "GELight5", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:03:29:08-01", "swversion": "1197632"}}`

Looks like there are issues with deserializing when the effect does not exist on a light!

**Comment by michielpost** [comment]
Ok thanks, made the effect optional so it won't crash anymore.

**Comment by niels9001** [comment]
Cool, thanks! New NuGet package with this fix coming up as well?

**Comment by michielpost** [comment]
Not right now, will come with a new release.
You can take the NuGet packages from the build server is you really need it right now: https://ci.appveyor.com/project/michielpost/q42-hueapi/build/artifacts
