### ISSUE TITLE
When CreateSceneAsync setting 'recycle' is required

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#56]
Didn't had this issue earlier, but my code stopped working (maybe due to firmware update).

{"lights":["3","2","5"],"recycle":true,"name":"My Scene" } /api/username/scenes // works
{"lights":["3","2","5"],"name":"My Scene" } to /api/username/scenes // does not work

With the 1.11 POST request recycle needs to be set. The API description mentions that the bool will be set automatically if not but looks like it doesn't.

Would be nice if the Q42.HueApi would set this to true or false if it is not being set. What do you guys think?

**Comment by michielpost** [comment]
Fixed it by sending the value false when recycle is null. New version is up on NuGet.
