### ISSUE TITLE
client.RegisterAsync, no timer/"button not pressed"

### ISSUE THREAD

**Issue by kordiak55** [Q42/Q42.HueApi#59]
Hello,

This could be due to my own ignorance but I'm struggling to use client.RegisterAsync. 

I keep getting "Button not pressed", the light doesn't blink on the bridge, but it makes sense that the command is being sent out, doesn't get a response, and returns "Button not pressed". 

Am I missing something simple, like a correct wait statement or something? 

```
    class Program
    {
        static void Main(string[] args)
        {
            Task tasker = thisDoesntWork();

            //thisWorks();

            Console.ReadLine();   
        }

        static async Task thisDoesntWork()
        {
        
            ILocalHueClient client = new LocalHueClient("192.168.1.3");
            string appKey = await client.RegisterAsync("mypersonalappname", "mydevicename");
            
            //Crash occures before this line, but I get "Button not pressed" in the debugger, so I think it's executing. 

            Console.WriteLine(appKey);

        }

        public static void thisWorks()
        {

            ILocalHueClient client = new LocalHueClient("192.168.1.3");

            client.Initialize("139f12ce32a30c473368dbe25f6586b");

            var command = new LightCommand();
            command.On = true;

            client.SendCommandAsync(command);

        }
    }
```

I'm able to use client.Initialize with a appKey I generated from the hue debug api, and I'm able to send basic light commands with your library, so I don't think this is a connection issue. 

Any help is greatly appreciated.

**Comment by michielpost** [comment]
You first need to press the button on the bridge and then send the command within 30 seconds, see the documentation here:
http://www.developers.meethue.com/documentation/configuration-api#71_create_user

Also see this example for using async and await in a console app:
http://stackoverflow.com/a/17630538

**Comment by kordiak55** [comment]
Worked like a charm, thank you sir!
