### ISSUE TITLE
GetLightAsync returns no light id

### ISSUE THREAD

**Issue by sdc4** [Q42/Q42.HueApi#60]
When GetLightAsync was called, the id of returned light is always "null". The Result GetLightsAsync, shows an valid id. 

![image](https://cloud.githubusercontent.com/assets/1159851/14234851/f312d532-f9ed-11e5-9b89-ffeaa2a20538.png)

**Comment by michielpost** [comment]
Thanks, fixed it.

**Comment by michielpost** [comment]
New version with this change is available on NuGet: https://www.nuget.org/packages/Q42.HueApi/
