### ISSUE TITLE
Win 10 Bug with System.Net.Http

### ISSUE THREAD

**Issue by gasagu** [Q42/Q42.HueApi#65]
I tried to use the Api in a Windows 10 universal app. Worked fine with widows forms but in the Win10 app i got an error from System.Net.Http while i tried to register my bridge.

There is a known bug with System.Net.Http under Win10.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/ff66088c-6705-40c0-b839-491b6ed6eb76/uwpwindows-10-bug-in-httpclienthttpwebrequest-when-using-network-credentials?forum=wpdevelop

**Comment by michielpost** [comment]
The issue you're referring to is about sending Network Credentials. This functionality is not used with the Hue bridge.

What's the error you're getting?
Does it only happen when you try to register with the bridge, or also with other API calls?

**Comment by gasagu** [comment]
When i try to recive the Appkey,
`var appKey = await client.RegisterAsync("Some Name", "SomePC");`
it throws me an  exception.
> System.Net.Http.HttpRequestException was unhandled by user code
>   HResult=-2147024891
>   Message=An error occurred while sending the request.
>   Source=System.Net.Http
>   StackTrace:
>        at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Q42.HueApi.LocalHueClient.<RegisterAsync>d__8.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>        at HuCoV2.MainPage.<registerBridge>d__4.MoveNext()
>   InnerException: 
>        HResult=-2147024891
>        Message=Zugriff verweigert
> 
> A network capability is required to access this network resource
>        Source=""
>        StackTrace:
>             at Windows.Web.Http.Filters.HttpBaseProtocolFilter.SendRequestAsync(HttpRequestMessage request)
>             at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__1.MoveNext()
>          --- End of stack trace from previous location where exception was thrown ---
>             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>             at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()
>        InnerException: 

At first i thougt my application needet more rights and i checked the Package.appxmanifes. Networking rights were already granted.
I tried to initialize directly with an appkey i got from a former testapplication under WPF.
```
ILocalHueClient client = new LocalHueClient("19---------9");
client.Initialize("wyZJbM6-------------------------------r4YtF86");
```
There i got no exception or error. But a simple test to turn off my lights didnt worked afterwise.
Under WPF i hat no problems at all. Really enjoyed your API but i want to use Cortana so i have to use UWP.

**Comment by michielpost** [comment]
It looks like you need to check the capability "Private Networks (Clients and Servers)" Only "Internet" is not enough.

**Comment by gasagu** [comment]
I did that already.
```
  <Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="internetClientServer" />
  </Capabilities>
```

**Comment by michielpost** [comment]
No, you need to have:
Private Networks (Clients and Servers):
`<Capability Name="privateNetworkClientServer" />`

**Comment by gasagu** [comment]
Thank you very much for the great and fast support. It worked, i have to work on my XAML skills.
Keep up the good work and have a nice day.

Greetings
