### ISSUE TITLE
Misleading method description

### ISSUE THREAD

**Issue by freeubi** [Q42/Q42.HueApi#67]
Hello,

i found a few errors in the descriptions:

-group.Action = Action property only filled when getting a single group
-group.Lights = Lights property only filled when getting a single group
etc.

They are misleading, i get the data with the client.GetLightsAsync() method, but jus wasted 2 hours of work cause of it...

**Comment by michielpost** [comment]
Thanks, this has probably been changed with one of the bridge firmware updates. I've updated the comments.
