### ISSUE TITLE
group ToHex() and ToRGB()

### ISSUE THREAD

**Issue by freeubi** [Q42/Q42.HueApi#68]
There is an extension method on the Group.Action status, ToHex() and ToRgb().

I think it is for give back the average color from lights in the group, but currently it return with black (r=0,g=0,b=0, and "000000").

**Comment by michielpost** [comment]
Just tested this and works fine.
The action property contains "The light state of one of the lamps in the group". So make sure all your lights in the group are on. That should work.

**Comment by freeubi** [comment]
I have only one light in the group, an Extended color light, modelid: "LST002".

With the light data request i got all the property right, but not in the group action.
I will look into today.

**Comment by freeubi** [comment]
Ok, its seems that the problem was that the light is off when i try to get the color.
Strange behaviour, the color doesnt depends on the on/off or brightness settings.
(The XY is filled when the light is off.)

**Comment by michielpost** [comment]
Yes, the color is based on the state, not just the XY, so if the light is off, it will return black als color.
