### ISSUE TITLE
Group Action isReachable(), isOn()

### ISSUE THREAD

**Issue by freeubi** [Q42/Q42.HueApi#69]
The group.Action has an IsReachable and an IsOn property but they are always false.

**Comment by michielpost** [comment]
The Action.On property is correctly set. The action property for a group contains "The light state of one of the lamps in the group.". So make sure all lights in the group are on.

IsReachable is indeed always false. The bridge does not return that value for a group. I'll make it a nullable property.

**Comment by freeubi** [comment]
I have only one light on my group, it is reachable and is on, but not in the returned data.

Currently i'm using a loop to get all the lights data from the group and set the propertys based on.
