### ISSUE TITLE
Lat / Long missing from SensorConfig with 3.1 version?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#77]
After upgrading to v3.1 I get the following error message:

'SensorConfig' does not contain a definition for 'Lat' and no extension method 'Lat'

**Comment by michielpost** [comment]
That's correct. They have been removed by Philips with Bridge API 1.15 (published 09/09/2016)
See the changelog: http://www.developers.meethue.com/documentation/changelog

**Comment by niels9001** [comment]
Ah, I see.

However, although getting the lat/lon is no longer supported (for privacy reasons), setting them still is (just like before, with the SensorConfig)!

E.g.:

PUT
/api/username/sensors/1/config

{"lat":"010.5186N"}


How does this work with the updated changes?

Niels

**Comment by michielpost** [comment]
Hm true, they are still in the SensorCommand, but you can't use that to update the SensorConfig. SensorCommand can only be used with schedules.

I've added them back for now and it's in NuGet version 3.1.1

Will do a big refactor of the SensorState and SensorConfig models next time.

**Comment by niels9001** [comment]
Thanks :)!
