### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException in GetSensors?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#78]
Seems there's a bug in the GetSensors call with the new API changes.

I get the following error:

> Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll

in 
`Sensor Sensor = JsonConvert.DeserializeObject<Sensor>(prop.Value.ToString());`

with this JSON:

`{
	"1": {
		"state": {
			"daylight": true,
			"lastupdated": "2016-09-20T05:55:00"
		},
		"config": {
			"on": true,
			"configured": true,
			"sunriseoffset": 30,
			"sunsetoffset": -30
		},
		"name": "Daylight",
		"type": "Daylight",
		"modelid": "PHDL00",
		"manufacturername": "Philips",
		"swversion": "1.0"
	},
	"2": {
		"state": {
			"buttonevent": 34,
			"lastupdated": "2016-09-20T05:39:27"
		},
		"config": {
			"on": true
		},
		"name": "Tap",
		"type": "ZGPSwitch",
		"modelid": "ZGPSWITCH",
		"manufacturername": "Philips",
		"uniqueid": "00:00:00:00:00:00:00:00-00"
	},
	"5": {
		"state": {
			"buttonevent": 4002,
			"lastupdated": "2016-09-20T08:38:42"
		},
		"config": {
			"on": true,
			"battery": 100,
			"reachable": true,
			"pending": []
		},
		"name": "Dimmer",
		"type": "ZLLSwitch",
		"modelid": "RWL021",
		"manufacturername": "Philips",
		"swversion": "5.45.1.17846",
		"uniqueid": "00:00:00:00:00:00:00:00-01"
	}
}`

**Comment by niels9001** [comment]
I double-checked with another system, and also the older version of the API. The bug is not occuring with the older version of the API, so I guess it has to do with the deserialization of the Sensor type, which was changed in the newer version. Hope this helps.

**Comment by michielpost** [comment]
Will have a look at this tomorow.

**Comment by michielpost** [comment]
Should be fixed in version 3.2.0 that's now on NuGet

**Comment by niels9001** [comment]
Yep, all works now. Thanks! I'm closing this issue

**Comment by StefanRademakers** [comment]
Seems there is another deserialization bug, at line:

Sensor scene = JsonConvert.DeserializeObject<Sensor> (prop.Value.ToString ());

The prop.value:

{
  "state": {
    "daylight": null,
    "lastupdated": "none"
  },
  "config": {
    "on": true,
    "configured": false,
    "sunriseoffset": 30,
    "sunsetoffset": -30
  },
  "name": "Daylight",
  "type": "Daylight",
  "modelid": "PHDL00",
  "manufacturername": "Philips",
  "swversion": "1.0"
}
