### ISSUE TITLE
What to use when 

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#84]
I'm trying to create a Hue Tap toggle button, and I need to set a flag to true/false within the action, like this:

`    {
            "address": "/sensors/7/state",
            "method": "PUT",
            "body": {
                "flag": true
            }
        }` 

What should I use (e.g. LightCommand or SceneCommand) to achieve this?

**Comment by michielpost** [comment]
This would be an `InternalBridgeCommand` with the Body set to `new SensorState() { Flag = true}` because the command goes to a sensor.
