### ISSUE TITLE
Setting CheckForUpdate results in an error:

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#85]
Setting CheckForUpdate results in an error:

`         BridgeConfigUpdate CheckForUpdate = new BridgeConfigUpdate() { SoftwareUpdate = new SoftwareUpdate() { CheckForUpdate = true } };

            HueResults x = await Client.UpdateBridgeConfigAsync(CheckForUpdate);`

= 

> {"swupdate":{"updatestate":0,"notify":false,"checkforupdate":true},"touchlink":false}

Result:

> [{"error":{"type":7,"address":"/config/updatestate","description":"invalid value, 0,, for parameter, updatestate"}},{"error":{"type":7,"address":"/config/swupdate/notify","description":"invalid value, false, for parameter, notify"}},{"success":{"/config/swupdate/checkforupdate":true}},{"error":{"type":7,"address":"/config/touchlink","description":"invalid value, false, for parameter, touchlink"}}]

**Comment by michielpost** [comment]
Should be fixed now in version 3.2.6
