### ISSUE TITLE
Request: add StoreLightState as action

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#86]
I'm trying to set the following in a Rule:

> "address": "/scenes/8mibZqD7HOsWpn4",
				"method": "PUT",
				"body": {
					"storelightstate": true
				}

E.g.:
`new InternalBridgeCommand() { Address = "/scenes/8mibZqD7HOsWpn4", Body = new Scene() { StoreLightState = true }, Method = HttpMethod.Put })`

**Comment by michielpost** [comment]
Ok, I've added it, not sure if it will work? 

If you want to have full control over your commands, you can use the GenericScheduleCommand:
```
dynamic dynamicCommand = new ExpandoObject();
dynamicCommand.storelightstate= true;
var jsonString = JsonConvert.SerializeObject(dynamicCommand);
var commandBody = new GenericScheduleCommand(jsonString);```

And then set this commandBody as the Body of the InternalBridgeCommand.

**Comment by michielpost** [comment]
SceneCommand now has a StoreLightState property. In NuGet release 3.2.6
