### ISSUE TITLE
UpdateSensorAsync can't update SensorConfig?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#88]
There does not seem to be a way to update the SensorConfig, am I right? I guess UpdateSensorAsync(string SensorID, SensorConfig Config) would be the most logical way?

**Comment by michielpost** [comment]
UpdateSensorAsync corresponds to this API call:
`/api/<username>/sensors/<id>`
https://www.developers.meethue.com/documentation/sensors-api#56_update_sensor
You can only change the name

If you want to Change the Sensor Config you can use ChangeSensorConfigAsync
https://www.developers.meethue.com/documentation/sensors-api#58_change_sensor_config

**Comment by niels9001** [comment]
Ah, sorry for the confusion!
