### ISSUE TITLE
Error when updating SensorConfig

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#89]
> "parameter, reachable, is not modifiable"
"parameter, battery, is not modifiable"

`Sensor selectedSensor = selectedSwitch.DataContext as Sensor;`
`HueResults x = await Client.ChangeSensorConfigAsync(selectedSensor.Id, selectedSensor.Config);`

Seems that the _reachable_ and _battery_ should be ignored.

**Comment by michielpost** [comment]
In the documentation battery is marked WO, Optional for Put Commands. Indicating they can be provided. But seems logical you can't update the battery status yourself.
https://developers.meethue.com/documentation/supported-sensors

If you make battery and reachable null, they won't be send to the bridge. I'll make an update so they will be automatically removed.

**Comment by michielpost** [comment]
https://github.com/Q42/Q42.HueApi/commit/59ced274d8b82e11ee788c2db1a58532c7701f7a

**Comment by michielpost** [comment]
Fixed in release 3.2.7, now on NuGet
