### ISSUE TITLE
GetSceneAsync() doesn't return lightstates?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#93]
The JSON call is right, the LightStates get ignored however and cannot be accessed:

`Scene x = await Client.GetSceneAsync(SelectedScene.Id);`

> /api/iTZfGk3w8ityIVSW4izaa-zFnBb7Y1KPqDluhC8x/scenes/dKDKY6a2DJwOrYw

> {"name":"Lentebloesem","lights":["1","4","6"],"owner":"Ftg8b0E4NVk3vVpodvV-Nh-rg8q3XfB0sDUZv3Hy","recycle":false,"locked":false,"appdata":{"version":1,"data":"4uvbC_r05_d18"},"picture":"","lastupdated":"2016-12-26T16:32:18","version":2,"lightstates":{"1":{"on":true,"bri":214,"xy":[0.5029,0.2661]},"4":{"on":true,"bri":214,"xy":[0.3944,0.2952]},"6":{"on":true,"bri":214,"xy":[0.3944,0.2952]}}}

**Comment by michielpost** [comment]
Fixed in version 2.3.8
