### ISSUE TITLE
UpdateSceneAsync() should ignore Id?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#94]
`await Client.UpdateSceneAsync(SelectedScene.Id, SelectedScene);`

sends out this JSON:

> {"Id":"dKDKY6a2DJwOrYw","name":"Lentebloesem","lights":["1","4","6"],"appdata":{"version":1,"data":"4uvbC_r05_d18"},"picture":""}

Bridge returns

> [
	{
		"error": {
			"type": 6,
			"address": "/scenes/dKDKY6a2DJwOrYw/Id",
			"description": "parameter, Id, not available"
		}
	}
]

Setting Id to null currently works as a workaround!

**Comment by michielpost** [comment]
Fixed in version 2.3.8
