### ISSUE TITLE
Q42.HueApi for Xamarin.iOS

### ISSUE THREAD

**Issue by s5zone** [Q42/Q42.HueApi#96]
I tried adding the Q42.HueApi to a Xamarin.iOS project and I got the following error:

Attempting to gather dependency information for package 'Q42.HueApi.3.2.8' with respect to project '<project name>', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 9.66 sec
Attempting to resolve dependencies for package 'Q42.HueApi.3.2.8' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Q42.HueApi.3.2.8'
Resolved actions to install package 'Q42.HueApi.3.2.8'
Found package 'Microsoft.Bcl.Build 1.0.14' in '<projectpath>\packages'.
Found package 'Microsoft.Bcl 1.1.10' in '<projectpath>\packages'.
Found package 'Microsoft.Net.Http 2.2.29' in '<projectpath>\packages'.
Found package 'Q42.HueApi.ColorConverters 3.0.0' in '<projectpath>\packages'.
Found package 'Q42.HueApi 3.2.8' in '<projectpath>\packages'.
Found package 'Newtonsoft.Json 9.0.1' in '<projectpath>\packages'.
Install failed. Rolling back...
Package 'Microsoft.Bcl.Build.1.0.14' does not exist in project '<project name>'
Removing package 'Microsoft.Bcl.Build.1.0.14' from folder '<projectpath>\packages'
Access to the path '<projectpath>\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.Tasks.dll' is denied.
Access to the path 'Microsoft.Bcl.Build.Tasks.dll' is denied.
Removed package 'Microsoft.Bcl.Build.1.0.14' from folder '<projectpath>\packages'
Executing nuget actions took 409.71 ms
Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
Time Elapsed: 00:00:15.2143885

**Comment by nolanblew** [comment]
Same for installing on Android in Xamarin

**Comment by nolanblew** [comment]
Apparently the minimum version of Microsoft.Bcl.Build that is required for the app is not compatible with Droid or iOS.

Installing the latest Bcl.Build package from NuGet first, *then* install Q42HueApi and that solves the issue

**Comment by michielpost** [comment]
I've added the latest Microsoft.Bcl.Build package to the Q42.HueApi nuspec file. Can you check if this fixes the issue? You can install Q42.HueApi 3.2.9
