### ISSUE TITLE
Manage multiple Philips Hue bridges

### ISSUE THREAD

**Issue by MiguelRipoll23** [Q42/Q42.HueApi#98]
I see that the method LocateBridgesAsync returns strings. I'm not quite sure if the bridge has a static IP address but is there any way to know their MAC address or get some kind of id to differentiate which bulbs belong to each bridge?

Thanks.

**Comment by freeubi** [comment]
The bridges doesnt have static IP, it can change. 
There is unique bridge id, so you can check that. Its called bridgeid.

More info here: https://developers.meethue.com/documentation/configuration-api   7.2

**Comment by MiguelRipoll23** [comment]
@freeubi this attribute only appears inside the RemoteHue class but looks like it can be accessed locally, so it looks like I just need to the HTTP request myself. 

Thanks for the info!

**Comment by freeubi** [comment]
There is a BridgeId in the BridgeConfig class. I think its available, but i cant check it right now :/

**Comment by michielpost** [comment]
See PR #99 
LocateBridgesAsync now returns a IP and a SerialNumber / BridgeId for each bridge

**Comment by michielpost** [comment]
New version is now on NuGet (3.3.0)

**Comment by MiguelRipoll23** [comment]
@michielpost I didn't see that PR, thank you!
